ALTER TABLE student ALTER COLUMN birthday DATE NOT NULL;

ALTER TABLE mark ADD CONSTRAINT GRADE_CHECK CHECK (mark IN (1, 2, 3, 4, 5));
ALTER TABLE mark ALTER COLUMN student_id BIGINT NOT NULL;
ALTER TABLE mark ALTER COLUMN subject_id BIGINT NOT NULL;

ALTER TABLE subject ADD CONSTRAINT GRADE_CHECK CHECK (grade IN (1,2,3,4,5,6,7,8,9,10));

ALTER TABLE paymenttype ADD CONSTRAINT NAME_UNIQUE UNIQUE(name);

ALTER TABLE payment ALTER COLUMN amount VARCHAR(45) NOT NULL;
ALTER TABLE payment ALTER COLUMN type_id BIGINT NOT NULL;
ALTER TABLE payment ALTER COLUMN payment_date BIGINT NOT NULL;